version: "3"
services: 
  app:
    container_name: rajni
    restart: always
    build: .
    ports:
      - "3001:3000"
    links:
      - mongo
  mongo: 
      container_name: rajni-mongo
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports: 
        - "27018:27017"
      volumes:
        - 'mongo:/data/db'
  volumes:
    mongo:
