apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: nodeapp
        image: rajnikanthdhoni/node1
        ports:
        - containerPort: 3000
